# Goal of the ETL Lesson

The main goal of this ETL pipelines lesson is to take the [World Bank Project data set](https://datacatalog.worldbank.org/dataset/world-bank-projects-operations) and merge this data with the [World Bank indicator data](https://data.worldbank.org/indicator/SP.POP.TOTL). Then you'll load the merged data into a database.

In the process, you'll need to transform these data sets in different ways. And finally, you'll code an ETL pipeline to extract, transform, and load the data all in one step.

# Extracting data from a csv file

The first step in an ETL pipeline is extraction. Data comes in all types of different formats, and you'll practice extracting data from csv files, JSON files, XML files, SQL databases, and the web.

In this first exercise, you'll practice extracting data from a CSV file and then navigating through the results. You'll see that extracting data is not always a straight-forward process.

This exercise contains a series of coding questions for you to solve. If you get stuck, there is a solution file called 1_csv_exercise_solution.ipynb. You can find this solution file by going to File->Open and then clicking on the file name.

# Part 1 projects_data.csv

You'll be using the following csv files:
* projects_data.csv
* population_data.csv

As a first step, try importing the projects data using the pandas [read_csv method](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html). The file path is just '../data/projects_data.csv'. You can see the file if you click on File->Open in the workspace and open the data folder.

In [1]:
# TODO: import the projects_data.csv file using the pandas library
# Store the results in the df_projects variable
import pandas as pd
df_projects = pd.read_csv('projects_data.csv')
df_projects.head()

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (44) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,...,mjtheme3name,mjtheme4name,mjtheme5name,location,GeoLocID,GeoLocName,Latitude,Longitude,Country,Unnamed: 56
0,P162228,Other,World;World,RE,Investment Project Financing,IN,C,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P163962,Africa,Democratic Republic of the Congo;Democratic Re...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P167672,South Asia,People's Republic of Bangladesh;People's Repub...,PE,Investment Project Financing,IN,NaN,Y,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P158768,South Asia,Islamic Republic of Afghanistan;Islamic Repu...,PE,Investment Project Financing,IN,A,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P161364,Africa,Federal Republic of Nigeria;Federal Republic o...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,0002327546!$!Ogun State!$!7!$!3.58333!$!NG;000...,0002327546;0002328925;0002565340;0002565343;00...,Ogun State;Niger State;Abia State;Edo;Kebbi St...,7;10;5.41667;6.5;11.5;8,3.58333;6;7.5;6;4;10.5,NG;NG;NG;NG;NG;NG,NaN

Did you get a DType warning? Read about what this warning is in the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.errors.DtypeWarning.html).

Pandas tries to figure out programatically the data type of each column (integer, float, boolean, string). In this case, pandas could not automatically figure out the data type. That is because some columns have more than one possible data types. In other words, this data is messy.

You can use the dtype option to specify the data type of each column. Because there are so many columns in this data set, you can set all columns to be strings at least for now.

Try reading in the data set again using the read_csv() method. This time, also use the option dtype=str so that pandas treats everything like a string.

In [2]:
# TODO: Read in the projects_data.csv file using the read_csv method 
# and dtype = str option
df_projects = pd.read_csv('projects_data.csv',dtype=str)
df_projects

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,...,mjtheme3name,mjtheme4name,mjtheme5name,location,GeoLocID,GeoLocName,Latitude,Longitude,Country,Unnamed: 56
0,P162228,Other,World;World,RE,Investment Project Financing,IN,C,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P163962,Africa,Democratic Republic of the Congo;Democratic Re...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P167672,South Asia,People's Republic of Bangladesh;People's Repub...,PE,Investment Project Financing,IN,NaN,Y,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P158768,South Asia,Islamic Republic of Afghanistan;Islamic Repu...,PE,Investment Project Financing,IN,A,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P161364,Africa,Federal Republic of Nigeria;Federal Republic o...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,0002327546!$!Ogun State!$!7!$!3.58333!$!NG;000...,0002327546;0002328925;0002565340;0002565343;00...,Ogun State;Niger State;Abia State;Edo;Kebbi St...,7;10;5.41667;6.5;11.5;8,3.58333;6;7.5;6;4;10.5,NG;NG;NG;NG;NG;NG,NaN
5,P161483,Middle East and North Africa,Republic of Tunisia;Republic of Tunisia,PE,Development Policy Lending,AD,NaN,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,P161885,Africa,Federal Republic of Nigeria;Federal Republic o...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,P162069,Africa,Federal Republic of Nigeria;Federal Republic o...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,P163540,Africa,Federal Republic of Nigeria;Federal Republic o...,PE,Investment Project Financing,IN,C,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,P163576,Middle East and North Africa,Lebanese Republic;Lebanese Republic,PE,Program-for-Results,PR,NaN,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,P163721,South Asia,Democratic Socialist Republic of Sri Lan;Democ...,PE,Investment Project Financing,IN,C,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,P164082,Africa,Federal Republic of Nigeria;Federal Republic o...,PE,Investment Project Financing,IN,NaN,Y,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,P164783,South Asia,Nepal;Nepal,RE,Investment Project Financing,IN,C,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,P165247,Africa,Federal Republic of Nigeria;Federal Republic o...,PE,Investment Project Financing,IN,NaN,Y,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,P165286,Europe and Central Asia,Kyrgyz Republic;Kyrgyz Republic,RE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,P166360,Middle East and North Africa,Hashemite Kingdom of Jordan;Hashemite Kingdom ...,PE,Development Policy Lending,AD,NaN,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,P166734,East Asia and Pacific,Republic of the Union of Myanmar;Republic of t...,RE,Investment Project Financing,IN,NaN,Y,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,P167000,Middle East and North Africa,Arab Republic of Egypt;Arab Republic of Egypt,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,P163732,Africa,United Republic of Tanzania;United Republic of...,PE,Program-for-Results,PR,NaN,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,P163829,Africa,Federal Democratic Republic of Ethiopia;Federa...,PE,Program-for-Results,PR,NaN,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,P164345,Africa,Burkina Faso;Burkina Faso,PE,Program-for-Results,PR,NaN,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,P166019,Europe and Central Asia,Republic of Uzbekistan;Republic of Uzbekistan,PE,Development Policy Lending,AD,NaN,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,P166303,Europe and Central Asia,Romania;Romania,PE,Development Policy Lending,AD,NaN,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,P164429,Africa,Federal Democratic Republic of Ethiopia;Federa...,PE,Investment Project Financing,IN,NaN,Y,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,P163756,Africa,Republic of Ghana;Republic of Ghana,RE,Investment Project Financing,IN,C,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,P158756,Latin America and Caribbean,Republic of Ecuador;Republic of Ecuador,PE,Investment Project Financing,IN,A,Y,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,P160162,East Asia and Pacific,Socialist Republic of Vietnam;Socialist Republ...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,P163138,East Asia and Pacific,People's Republic of China;People's Republic o...,PE,Program-for-Results,PR,NaN,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,P164262,Africa,Republic of Senegal;Republic of Senegal,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,P164289,Latin America and Caribbean,Grenada;Grenada,PE,Development Policy Lending,AD,NaN,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18218,P000659,Africa,Federal Democratic Republic of Ethiopia;Federa...,PE,Specific Investment Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18219,P008109,Latin America and Caribbean,Oriental Republic of Uruguay;Oriental Republic...,PE,Sector Investment and Maintenance Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18220,P037342,East Asia and Pacific,Commonwealth of Australia;Commonwealth of Aust...,PE,Structural Adjustment Loan,AD,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18221,P008872,Europe and Central Asia,Republic of Turkey;Republic of Turkey,PE,Specific Investment Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18222,P008874,Europe and Central Asia,Republic of Turkey;Republic of Turkey,PE,Specific Investment Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18223,P005231,Middle East and North Africa,Republic of Iraq;Republic of Iraq,PE,NaN,NaN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18224,P006215,Latin America and Caribbean,Federative Republic of Brazil;Federative Repub...,PE,Specific Investment Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18225,P007499,Latin America and Caribbean,United Mexican States;United Mexican States,PE,Sector Investment and Maintenance Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18226,P009587,South Asia,Republic of India;Republic of India,PE,Specific Investment Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18227,P007137,Latin America and Caribbean,Republic of El Salvador;Republic of El Salvador,PE,Specific Investment Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18228,P009133,Europe and Central Asia,Socialist Federal Republic of Yugoslavia;Socia...,PE,Specific Investment Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18229,P037365,Europe and Central Asia,Republic of Finland;Republic of Finland,PE,Specific Investment Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18230,P009586,South Asia,Republic of India;Republic of India,PE,Sector Investment and Maintenance Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18231,P006682,Latin America and Caribbean,Republic of Colombia;Republic of Colombia,PE,Sector Investment and Maintenance Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18232,P009588,South Asia,Republic of India;Republic of India,PE,Specific Investment Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18233,P037366,Europe and Central Asia,Republic of Finland;Republic of Finland,PE,Sector Investment and Maintenance Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18234,P037456,Europe and Central Asia,Kingdom of the Netherlands;Kingdom of the Neth...,PE,Sector Investment and Maintenance Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18235,P037358,Europe and Central Asia,Kingdom of Belgium;Kingdom of Belgium,PE,Sector Investment and Maintenance Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18236,P006214,Latin America and Caribbean,Federative Republic of Brazil;Federative Repub...,PE,Sector Investment and Maintenance Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18237,P007497,Latin America and Caribbean,United Mexican States;United Mexican States,PE,Sector Investment and Maintenance Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18238,P007498,Latin America and Caribbean,United Mexican States;United Mexican States,PE,Sector Investment and Maintenance Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18239,P037453,Europe and Central Asia,Kingdom of the Netherlands;Kingdom of the Neth...,PE,Sector Investment and Maintenance Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18240,P037454,Europe and Central Asia,Kingdom of the Netherlands;Kingdom of the Neth...,PE,Sector Investment and Maintenance Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18241,P037455,Europe and Central Asia,Kingdom of the Netherlands;Kingdom of the Neth...,PE,Sector Investment and Maintenance Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18242,P006577,Latin America and Caribbean,Republic of Chile;Republic of Chile,PE,Financial Intermediary Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18243,P006578,Latin America and Caribbean,Republic of Chile;Republic of Chile,PE,Specific Investment Loan,IN,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18244,P037451,Europe and Central Asia,Grand Duchy of Luxembourg;Grand Duchy of Luxem...,PE,Structural Adjustment Loan,AD,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18245,P037362,Europe and Central Asia,Kingdom of Denmark;Kingdom of Denmark,PE,Structural Adjustment Loan,AD,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18246,P037452,Europe and Central Asia,Kingdom of the Netherlands;Kingdom of the Neth...,PE,Structural Adjustment Loan,AD,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18247,P037383,Europe and Central Asia,French Republic;French Republic,PE,Structural Adjustment Loan,AD,NaN,N,L,Closed,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Run the cell below to see what the data looks like
df_projects.head()

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,...,mjtheme3name,mjtheme4name,mjtheme5name,location,GeoLocID,GeoLocName,Latitude,Longitude,Country,Unnamed: 56
0,P162228,Other,World;World,RE,Investment Project Financing,IN,C,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P163962,Africa,Democratic Republic of the Congo;Democratic Re...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P167672,South Asia,People's Republic of Bangladesh;People's Repub...,PE,Investment Project Financing,IN,NaN,Y,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P158768,South Asia,Islamic Republic of Afghanistan;Islamic Repu...,PE,Investment Project Financing,IN,A,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P161364,Africa,Federal Republic of Nigeria;Federal Republic o...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,0002327546!$!Ogun State!$!7!$!3.58333!$!NG;000...,0002327546;0002328925;0002565340;0002565343;00...,Ogun State;Niger State;Abia State;Edo;Kebbi St...,7;10;5.41667;6.5;11.5;8,3.58333;6;7.5;6;4;10.5,NG;NG;NG;NG;NG;NG,NaN

In [4]:
# TODO: count the number of null values in the data set
# HINT: use the isnull() and sum() methods
df_projects.isnull().sum()

id                              0
regionname                      0
countryname                     0
prodline                        0
lendinginstr                  246
lendinginstrtype              246
envassesmentcategorycode     5811
supplementprojectflg           53
productlinetype                 0
projectstatusdisplay            4
status                          4
project_name                    0
boardapprovaldate            1504
board_approval_month         1504
closingdate                  3349
lendprojectcost               125
ibrdcommamt                     0
idacommamt                      0
totalamt                        0
grantamt                        0
borrower                     5919
impagency                    6097
url                             0
projectdoc                  18248
majorsector_percent         18248
sector1                         0
sector2                      8721
sector3                     11761
sector4                     13872
sector5                     15535
sector                        638
mjsector1                   18248
mjsector2                   18248
mjsector3                   18248
mjsector4                   18248
mjsector5                   18248
mjsector                      638
theme1                          0
theme2                       8395
theme3                      10764
theme4                      13014
theme5                      15320
theme                       18248
goal                         6115
financier                   11188
mjtheme1name                18248
mjtheme2name                18248
mjtheme3name                18248
mjtheme4name                18248
mjtheme5name                18248
location                    13922
GeoLocID                    13922
GeoLocName                  13923
Latitude                    13922
Longitude                   13922
Country                     14045
Unnamed: 56                 18248
dtype: int64

Notice that the number 18248 shows up multiple times. There is also a countryname column with 0 missing values and a Country column with 14045 missing values. This data set clearly has some issues that will need to be solved in the transform part of the pipeline.

Next, output the shape of the data frame.

In [5]:
# TODO: output the shape of the data frame
df_projects.shape

(18248, 57)

There are 18248 rows in this data set. Considering many columns had 18248 NaN values, many columns in the data set are filled completely with NaN values.

# Part 2 population_data.csv

Next, use the pandas read_csv method to read in the population_data.csv file. The path to this file is "../data/population_data.csv". When you try to read in this data set using pandas, you'll get an error because there is something wrong with the data.

In [6]:
# TODO: read in the population_data.csv file using the read_csv() method
# Put the results in a variable called df_population
df_population = pd.read_csv('population_data.csv')

ParserError: Error tokenizing data. C error: Expected 3 fields in line 5, saw 63

There is something wrong with this data set. You should see an error that says "expected 3 fields in line 5, saw 63". What might have happened? Try printing out the first few lines of the data file to see what the issue might be.

In [7]:
# TODO: Print out the first 10 lines of the data set, line by line.
# HINT: You can't use the read_csv method from pandas
# HINT: to do this manually, you'll need to use pure Python
# HINT: the open(), readline(), and close() methods should be helpful
# HINT: Use a for loop
df_population=open('population_data.csv','r')
df_population.readline()
for i in range(10):
    print('line',i,':',df_population.readline())
df_population.close()

line 0 :

line 1 : "Last Updated Date","2018-06-28",

line 2 :

line 3 : "Country Name","Country Code","Indicator Name","Indicator Code","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017",

line 4 : "Aruba","ABW","Population, total","SP.POP.TOTL","54211","55438","56225","56695","57032","57360","57715","58055","58386","58726","59063","59440","59840","60243","60528","60657","60586","60366","60103","59980","60096","60567","61345","62201","62836","63026","62644","61833","61079","61032","62149","64622","68235","72504","76700","80324","83200","85451","87277","89005","90853","92898","94992","97017","98737","100031","100832","101220","101353","101453","101669","102053","102577","103187","103795","104341","104822","105264",

line 5 : "Afghanistan","AFG","Population, total","SP.POP.TOTL","8996351","9166764","9345868","9533954","9731361","9938414","10152331","10372630","10604346","10854428","11126123","11417825","11721940","12027822","12321541","12590286","12840299","13067538","13237734","13306695","13248370","13053954","12749645","12389269","12047115","11783050","11601041","11502761","11540888","11777609","12249114","12993657","13981231","15095099","16172719","17099541","17822884","18381605","18863999","19403676","20093756","20966463","21979923","23064851","24118979","25070798","25893450","26616792","27294031","28004331","28803167","29708599","30696958","31731688","32758020","33736494","34656032","35530081",

line 6 : "Angola","AGO","Population, total","SP.POP.TOTL","5643182","5753024","5866061","5980417","6093321","6203299","6309770","6414995","6523791","6642632","6776381","6927269","7094834","7277960","7474338","7682479","7900997","8130988","8376147","8641521","8929900","9244507","9582156","9931562","10277321","10609042","10921037","11218268","11513968","11827237","12171441","12553446","12968345","13403734","13841301","14268994","14682284","15088981","15504318","15949766","16440924","16983266","17572649","18203369","18865716","19552542","20262399","20997687","21759420","22549547","23369131","24218565","25096150","25998340","26920466","27859305","28813463","29784193",

line 7 : "Albania","ALB","Population, total","SP.POP.TOTL","1608800","1659800","1711319","1762621","1814135","1864791","1914573","1965598","2022272","2081695","2135479","2187853","2243126","2296752","2350124","2404831","2458526","2513546","2566266","2617832","2671997","2726056","2784278","2843960","2904429","2964762","3022635","3083605","3142336","3227943","3286542","3266790","3247039","3227287","3207536","3187784","3168033","3148281","3128530","3108778","3089027","3060173","3051010","3039616","3026939","3011487","2992547","2970017","2947314","2927519","2913021","2905195","2900401","2895092","2889104","2880703","2876101","2873457",

line 8 : "Andorra","AND","Population, total","SP.POP.TOTL","13411","14375","15370","16412","17469","18549","19647","20758","21890","23058","24276","25559","26892","28232","29520","30705","31777","32771","33737","34818","36067","37500","39114","40867","42706","44600","46517","48455","50434","52448","54509","56671","58888","60971","62677","63850","64360","64327","64142","64370","65390","67341","70049","73182","76244","78867","80991","82683","83861","84462","84449","83751","82431","80788","79223","78014","77281","76965",

line 9 : "Arab World","ARB","Population, total","SP.POP.TOTL","92490932","95044497","97682294","100411076","103239902","106174988","109230593","112406932","115680165","119016542","122398374","125807419","129269375","132863416","136696761","140843298","145332378","150133054","155183724","160392488","165689490","171051950","176490084","182005827","187610756","193310301","199093767","204942549","210844771","216787402","224735446","230829868","235037179","241286091","247435930","255029671","260843462","266575075","272235146","277962869","283832016","289850357","296026575","302434519","309162029","316264728","323773264","331653797","339825483","348145094","356508908","364895878","373306993","381702086","390043028","398304960","406452690","414491886",

The first four lines in the file are not properly formatted and don't contain data. Next, read in the data using the read_csv method. But this time, use the skiprows option.

In [8]:
# TODO: read in population data skipping the first four rows
# Put the results in a variable called df_population

df_population = pd.read_csv('population_data.csv',skiprows=4)
df_population

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
0,Aruba,ABW,"Population, total",SP.POP.TOTL,5.421100e+04,5.543800e+04,5.622500e+04,5.669500e+04,5.703200e+04,5.736000e+04,...,1.014530e+05,1.016690e+05,1.020530e+05,1.025770e+05,1.031870e+05,1.037950e+05,1.043410e+05,1.048220e+05,1.052640e+05,NaN
1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8.996351e+06,9.166764e+06,9.345868e+06,9.533954e+06,9.731361e+06,9.938414e+06,...,2.800433e+07,2.880317e+07,2.970860e+07,3.069696e+07,3.173169e+07,3.275802e+07,3.373649e+07,3.465603e+07,3.553008e+07,NaN
2,Angola,AGO,"Population, total",SP.POP.TOTL,5.643182e+06,5.753024e+06,5.866061e+06,5.980417e+06,6.093321e+06,6.203299e+06,...,2.254955e+07,2.336913e+07,2.421856e+07,2.509615e+07,2.599834e+07,2.692047e+07,2.785930e+07,2.881346e+07,2.978419e+07,NaN
3,Albania,ALB,"Population, total",SP.POP.TOTL,1.608800e+06,1.659800e+06,1.711319e+06,1.762621e+06,1.814135e+06,1.864791e+06,...,2.927519e+06,2.913021e+06,2.905195e+06,2.900401e+06,2.895092e+06,2.889104e+06,2.880703e+06,2.876101e+06,2.873457e+06,NaN
4,Andorra,AND,"Population, total",SP.POP.TOTL,1.341100e+04,1.437500e+04,1.537000e+04,1.641200e+04,1.746900e+04,1.854900e+04,...,8.446200e+04,8.444900e+04,8.375100e+04,8.243100e+04,8.078800e+04,7.922300e+04,7.801400e+04,7.728100e+04,7.696500e+04,NaN
5,Arab World,ARB,"Population, total",SP.POP.TOTL,9.249093e+07,9.504450e+07,9.768229e+07,1.004111e+08,1.032399e+08,1.061750e+08,...,3.481451e+08,3.565089e+08,3.648959e+08,3.733070e+08,3.817021e+08,3.900430e+08,3.983050e+08,4.064527e+08,4.144919e+08,NaN
6,United Arab Emirates,ARE,"Population, total",SP.POP.TOTL,9.263400e+04,1.010780e+05,1.124720e+05,1.255660e+05,1.385290e+05,1.503620e+05,...,7.666393e+06,8.270684e+06,8.672475e+06,8.900453e+06,9.006263e+06,9.070867e+06,9.154302e+06,9.269612e+06,9.400145e+06,NaN
7,Argentina,ARG,"Population, total",SP.POP.TOTL,2.061908e+07,2.095308e+07,2.128768e+07,2.162184e+07,2.195393e+07,2.228339e+07,...,4.079941e+07,4.122389e+07,4.165688e+07,4.209674e+07,4.253992e+07,4.298152e+07,4.341776e+07,4.384743e+07,4.427104e+07,NaN
8,Armenia,ARM,"Population, total",SP.POP.TOTL,1.874120e+06,1.941491e+06,2.009526e+06,2.077575e+06,2.144998e+06,2.211316e+06,...,2.888584e+06,2.877311e+06,2.875581e+06,2.881922e+06,2.893509e+06,2.906220e+06,2.916950e+06,2.924816e+06,2.930450e+06,NaN
9,American Samoa,ASM,"Population, total",SP.POP.TOTL,2.001300e+04,2.048600e+04,2.111700e+04,2.188200e+04,2.269800e+04,2.352000e+04,...,5.622700e+04,5.563700e+04,5.532000e+04,5.523000e+04,5.530700e+04,5.543700e+04,5.553700e+04,5.559900e+04,5.564100e+04,NaN
10,Antigua and Barbuda,ATG,"Population, total",SP.POP.TOTL,5.533900e+04,5.614400e+04,5.714400e+04,5.829400e+04,5.952400e+04,6.078100e+04,...,9.358100e+04,9.466100e+04,9.571900e+04,9.677700e+04,9.782400e+04,9.887500e+04,9.992300e+04,1.009630e+05,1.020120e+05,NaN
11,Australia,AUS,"Population, total",SP.POP.TOTL,1.027648e+07,1.048300e+07,1.074200e+07,1.095000e+07,1.116700e+07,1.138800e+07,...,2.169170e+07,2.203175e+07,2.234002e+07,2.274248e+07,2.314590e+07,2.350414e+07,2.385078e+07,2.421081e+07,2.459893e+07,NaN
12,Austria,AUT,"Population, total",SP.POP.TOTL,7.047539e+06,7.086299e+06,7.129864e+06,7.175811e+06,7.223801e+06,7.270889e+06,...,8.343323e+06,8.363404e+06,8.391643e+06,8.429991e+06,8.479823e+06,8.546356e+06,8.642699e+06,8.736668e+06,8.809212e+06,NaN
13,Azerbaijan,AZE,"Population, total",SP.POP.TOTL,3.895396e+06,4.030320e+06,4.171425e+06,4.315128e+06,4.456689e+06,4.592610e+06,...,8.947243e+06,9.054332e+06,9.173082e+06,9.295784e+06,9.416801e+06,9.535079e+06,9.649341e+06,9.757812e+06,9.862429e+06,NaN
14,Burundi,BDI,"Population, total",SP.POP.TOTL,2.786106e+06,2.839666e+06,2.893669e+06,2.949926e+06,3.010859e+06,3.077876e+06,...,8.489031e+06,8.766930e+06,9.043508e+06,9.319710e+06,9.600186e+06,9.891790e+06,1.019927e+07,1.052412e+07,1.086424e+07,NaN
15,Belgium,BEL,"Population, total",SP.POP.TOTL,9.153489e+06,9.183948e+06,9.220578e+06,9.289770e+06,9.378113e+06,9.463667e+06,...,1.079649e+07,1.089559e+07,1.104774e+07,1.112825e+07,1.118282e+07,1.120906e+07,1.127420e+07,1.133142e+07,1.137207e+07,NaN
16,Benin,BEN,"Population, total",SP.POP.TOTL,2.431622e+06,2.465867e+06,2.502896e+06,2.542859e+06,2.585965e+06,2.632356e+06,...,8.944706e+06,9.199259e+06,9.460802e+06,9.729160e+06,1.000445e+07,1.028671e+07,1.057595e+07,1.087230e+07,1.117569e+07,NaN
17,Burkina Faso,BFA,"Population, total",SP.POP.TOTL,4.829288e+06,4.894580e+06,4.960326e+06,5.027821e+06,5.098890e+06,5.174870e+06,...,1.514110e+07,1.560522e+07,1.608190e+07,1.657122e+07,1.707272e+07,1.758598e+07,1.811062e+07,1.864643e+07,1.919338e+07,NaN
18,Bangladesh,BGD,"Population, total",SP.POP.TOTL,4.819975e+07,4.959280e+07,5.103014e+07,5.253242e+07,5.412910e+07,5.583404e+07,...,1.504547e+08,1.521491e+08,1.539119e+08,1.557271e+08,1.575713e+08,1.594053e+08,1.612009e+08,1.629516e+08,1.646698e+08,NaN
19,Bulgaria,BGR,"Population, total",SP.POP.TOTL,7.867374e+06,7.943118e+06,8.012946e+06,8.078145e+06,8.144340e+06,8.204168e+06,...,7.444443e+06,7.395599e+06,7.348328e+06,7.305888e+06,7.265115e+06,7.223938e+06,7.177991e+06,7.127822e+06,7.075991e+06,NaN
20,Bahrain,BHR,"Population, total",SP.POP.TOTL,1.624270e+05,1.678940e+05,1.731440e+05,1.781400e+05,1.828870e+05,1.874310e+05,...,1.185029e+06,1.240862e+06,1.278269e+06,1.300217e+06,1.315411e+06,1.336397e+06,1.371855e+06,1.425171e+06,1.492584e+06,NaN
21,"Bahamas, The",BHS,"Population, total",SP.POP.TOTL,1.095280e+05,1.151080e+05,1.210830e+05,1.273330e+05,1.336980e+05,1.400540e+05,...,3.548560e+05,3.608320e+05,3.665680e+05,3.720390e+05,3.772400e+05,3.821690e+05,3.868380e+05,3.912320e+05,3.953610e+05,NaN
22,Bosnia and Herzegovina,BIH,"Population, total",SP.POP.TOTL,3.225668e+06,3.288602e+06,3.353226e+06,3.417574e+06,3.478995e+06,3.535640e+06,...,3.746561e+06,3.722084e+06,3.688865e+06,3.648200e+06,3.604999e+06,3.566002e+06,3.535961e+06,3.516816e+06,3.507017e+06,NaN
23,Belarus,BLR,"Population, total",SP.POP.TOTL,8.198000e+06,8.271216e+06,8.351928e+06,8.437232e+06,8.524224e+06,8.610000e+06,...,9.506765e+06,9.490583e+06,9.473172e+06,9.464495e+06,9.465997e+06,9.474511e+06,9.489616e+06,9.501534e+06,9.507875e+06,NaN
24,Belize,BLZ,"Population, total",SP.POP.TOTL,9.206400e+04,9.470300e+04,9.738400e+04,1.001640e+05,1.030690e+05,1.061190e+05,...,3.139290e+05,3.216080e+05,3.291920e+05,3.367010e+05,3.441810e+05,3.516940e+05,3.592880e+05,3.669540e+05,3.746810e+05,NaN
25,Bermuda,BMU,"Population, total",SP.POP.TOTL,4.440000e+04,4.550000e+04,4.660000e+04,4.770000e+04,4.890000e+04,5.010000e+04,...,6.563600e+04,6.512400e+04,6.456400e+04,6.479800e+04,6.500100e+04,6.513900e+04,6.523900e+04,6.534100e+04,6.544100e+04,NaN
26,Bolivia,BOL,"Population, total",SP.POP.TOTL,3.693449e+06,3.764813e+06,3.838097e+06,3.913395e+06,3.990857e+06,4.070590e+06,...,9.758748e+06,9.918242e+06,1.007834e+07,1.023900e+07,1.040026e+07,1.056216e+07,1.072470e+07,1.088788e+07,1.105160e+07,NaN
27,Brazil,BRA,"Population, total",SP.POP.TOTL,7.220755e+07,7.435176e+07,7.657325e+07,7.885402e+07,8.116865e+07,8.349802e+07,...,1.948960e+08,1.967963e+08,1.986867e+08,2.005610e+08,2.024086e+08,2.042131e+08,2.059621e+08,2.076529e+08,2.092883e+08,NaN
28,Barbados,BRB,"Population, total",SP.POP.TOTL,2.309390e+05,2.316780e+05,2.325860e+05,2.335870e+05,2.345470e+05,2.353740e+05,...,2.784700e+05,2.795690e+05,2.806010e+05,2.815850e+05,2.825090e+05,2.833850e+05,2.842170e+05,2.849960e+05,2.857190e+05,NaN
29,Brunei Darussalam,BRN,"Population, total",SP.POP.TOTL,8.174500e+04,8.559600e+04,8.951600e+04,9.357600e+04,9.784800e+04,1.024250e+05,...,3.837720e+05,3.886620e+05,3.940130e+05,3.997480e+05,4.057160e+05,4.117040e+05,4.175420e+05,4.231960e+05,4.286970e+05,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,"Population, total",SP.POP.TOTL,2.103576e+08,2.162859e+08,2.223965e+08,2.286630e+08,2.350485e+08,2.415251e+08,...,5.731253e+08,5.802468e+08,5.873151e+08,5.943307e+08,6.012772e+08,6.081360e+08,6.148920e+08,6.215349e+08,6.280598e+08,NaN
235,Timor-Leste,TLS,"Population, total",SP.POP.TOTL,4.999500e+05,5.088450e+05,5.181070e+05,5.277490e+05,5.377860e+05,5.482180e+05,...,1.092021e+06,1.109591e+06,1.131523e+06,1.156760e+06,1.184366e+06,1.212814e+06,1.240977e+06,1.268671e+06,1.296311e+06,NaN
236,Middle East & North Africa (IDA & IBRD countries),TMN,"Population, total",SP.POP.TOTL,9.783777e+07,1.004585e+08,1.031472e+08,1.059144e+08,1.087749e+08,1.117382e+08,...,3.257867e+08,3.317705e+08,3.378950e+08,3.441488e+08,3.504715e+08,3.567833e+08,3.630272e+08,3.691675e+08,3.752170e+08,NaN
237,Tonga,TON,"Population, total",SP.POP.TOTL,6.160100e+04,6.374500e+04,6.625900e+04,6.900500e+04,7.175700e+04,7.436200e+04,...,1.036040e+05,1.041370e+05,1.045770e+05,1.049510e+05,1.053280e+05,1.057820e+05,1.063640e+05,1.071220e+05,1.080200e+05,NaN
238,South Asia (IDA & IBRD),TSA,"Population, total",SP.POP.TOTL,5.718357e+08,5.838941e+08,5.964139e+08,6.093918e+08,6.228226e+08,6.367018e+08,...,1.607664e+09,1.630807e+09,1.653799e+09,1.676615e+09,1.699310e+09,1.721848e+09,1.744200e+09,1.766394e+09,1.788389e+09,NaN
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,"Population, total",SP.POP.TOTL,2.285860e+08,2.340086e+08,2.396471e+08,2.455033e+08,2.515764e+08,2.578686e+08,...,8.539537e+08,8.776284e+08,9.019899e+08,9.270399e+08,9.527341e+08,9.790179e+08,1.005850e+09,1.033213e+09,1.061108e+09,NaN
240,Trinidad and Tobago,TTO,"Population, total",SP.POP.TOTL,8.484790e+05,8.653600e+05,8.800230e+05,8.925690e+05,9.032750e+05,9.124170e+05,...,1.321618e+06,1.328100e+06,1.334788e+06,1.341588e+06,1.348248e+06,1.354493e+06,1.360092e+06,1.364962e+06,1.369125e+06,NaN
241,Tunisia,TUN,"Population, total",SP.POP.TOTL,4.176266e+06,4.235937e+06,4.303131e+06,4.377637e+06,4.458611e+06,4.545339e+06,...,1.052183e+07,1.063993e+07,1.076147e+07,1.088667e+07,1.101456e+07,1.114391e+07,1.127366e+07,1.140325e+07,1.153213e+07,NaN
242,Turkey,TUR,"Population, total",SP.POP.TOTL,2.747233e+07,2.814689e+07,2.883280e+07,2.953134e+07,3.024423e+07,3.097296e+07,...,7.133918e+07,7.232691e+07,7.340946e+07,7.456987e+07,7.578733e+07,7.703063e+07,7.827147e+07,7.951243e+07,8.074502e+07,NaN
243,Tuvalu,TUV,"Population, total",SP.POP.TOTL,6.104000e+03,6.246000e+03,6.389000e+03,6.538000e+03,6.684000e+03,6.815000e+03,...,1.044100e+04,1.053100e+04,1.062800e+04,1.072500e+04,1.081900e+04,1.090800e+04,1.100100e+04,1.109700e+04,1.119200e+04,NaN
244,Tanzania,TZA,"Population, total",SP.POP.TOTL,1.007451e+07,1.037340e+07,1.068391e+07,1.100590e+07,1.133910e+07,1.168353e+07,...,4.466423e+07,4.609859e+07,4.757090e+07,4.908300e+07,5.063660e+07,5.223487e+07,5.387996e+07,5.557220e+07,5.731002e+07,NaN
245,Uganda,UGA,"Population, total",SP.POP.TOTL,6.788214e+06,7.006633e+06,7.240174e+06,7.487429e+06,7.746198e+06,8.014401e+06,...,3.277190e+07,3.391513e+07,3.509365e+07,3.630680e+07,3.755373e+07,3.883334e+07,4.014487e+07,4.148796e+07,4.286296e+07,NaN
246,Ukraine,UKR,"Population, total",SP.POP.TOTL,4.266215e+07,4.320364e+07,4.374947e+07,4.428590e+07,4.479433e+07,4.526194e+07,...,4.605330e+07,4.587070e+07,4.570610e+07,4.559330e+07,4.548960e+07,4.527195e+07,4.515403e+07,4.500464e+07,4.483116e+07,NaN
247,Upper middle income,UMC,"Population, total",SP.POP.TOTL,1.150569e+09,1.154967e+09,1.171821e+09,1.200060e+09,1.227974e+09,1.256856e+09,...,2.422394e+09,2.440543e+09,2.459176e+09,2.478492e+09,2.498184e+09,2.517980e+09,2.537437e+09,2.556922e+09,2.576203e+09,NaN
248,Uruguay,URY,"Population, total",SP.POP.TOTL,2.538651e+06,2.571690e+06,2.603887e+06,2.635129e+06,2.665390e+06,2.694537e+06,...,3.362755e+06,3.374415e+06,3.385624e+06,3.396777e+06,3.408005e+06,3.419546e+06,3.431552e+06,3.444006e+06,3.456750e+06,NaN
249,United States,USA,"Population, total",SP.POP.TOTL,1.806710e+08,1.836910e+08,1.865380e+08,1.892420e+08,1.918890e+08,1.943030e+08,...,3.067715e+08,3.093384e+08,3.116443e+08,3.139933e+08,3.162345e+08,3.186225e+08,3.210398e+08,3.234059e+08,3.257192e+08,NaN
250,Uzbekistan,UZB,"Population, total",SP.POP.TOTL,8.549493e+06,8.837349e+06,9.138097e+06,9.454250e+06,9.788986e+06,1.014374e+07,...,2.776740e+07,2.856240e+07,2.933940e+07,2.977450e+07,3.024320e+07,3.075770e+07,3.129890e+07,3.184790e+07,3.238720e+07,NaN
251,St. Vincent and the Grenadines,VCT,"Population, total",SP.POP.TOTL,8.094900e+04,8.214200e+04,8.320600e+04,8.416700e+04,8.506900e+04,8.597000e+04,...,1.092530e+05,1.093150e+05,1.093410e+05,1.093280e+05,1.093200e+05,1.093570e+05,1.094550e+05,1.096430e+05,1.098970e+05,NaN
252,"Venezuela, RB",VEN,"Population, total",SP.POP.TOTL,8.146847e+06,8.461685e+06,8.790589e+06,9.130349e+06,9.476252e+06,9.824692e+06,...,2.858732e+07,2.902803e+07,2.946329e+07,2.989308e+07,3.031785e+07,3.073838e+07,3.115513e+07,3.156818e+07,3.197706e+07,NaN
253,British Virgin Islands,VGB,"Population, total",SP.POP.TOTL,8.033000e+03,8.155000e+03,8.298000e+03,8.452000e+03,8.627000e+03,8.814000e+03,...,2.644700e+04,2.722400e+04,2.790100e+04,2.850900e+04,2.905600e+04,2.958800e+04,3.011300e+04,3.066100e+04,3.119600e+04,NaN
254,Virgin Islands (U.S.),VIR,"Population, total",SP.POP.TOTL,3.250000e+04,3.430000e+04,3.500000e+04,3.980000e+04,4.080000e+04,4.350000e+04,...,1.084050e+05,1.083580e+05,1.082920e+05,1.081910e+05,1.080440e+05,1.078840e+05,1.077100e+05,1.075100e+05,1.072680e+05,NaN
255,Vietnam,VNM,"Population, total",SP.POP.TOTL,3.267063e+07,3.366677e+07,3.468416e+07,3.572209e+07,3.678098e+07,3.786001e+07,...,8.756541e+07,8.847251e+07,8.943664e+07,9.045188e+07,9.149772e+07,9.254492e+07,9.357157e+07,9.456907e+07,9.554080e+07,NaN
256,Vanuatu,VUT,"Population, total",SP.POP.TOTL,6.369900e+04,6.571300e+04,6.780800e+04,6.996400e+04,7.213100e+04,7.428900e+04,...,2.307850e+05,2.362950e+05,2.418710e+05,2.474850e+05,2.531420e+05,2.588500e+05,2.646030e+05,2.704020e+05,2.762440e+05,NaN
257,World,WLD,"Population, total",SP.POP.TOTL,3.032160e+09,3.073369e+09,3.126510e+09,3.191786e+09,3.257460e+09,3.324545e+09,...,6.849569e+09,6.932870e+09,7.014984e+09,7.099558e+09,7.185138e+09,7.271323e+09,7.357559e+09,7.444157e+09,7.530360e+09,NaN
258,Samoa,WSM,"Population, total",SP.POP.TOTL,1.086460e+05,1.121190e+05,1.157880e+05,1.195610e+05,1.233540e+05,1.270680e+05,...,1.848260e+05,1.862050e+05,1.876650e+05,1.891940e+05,1.907570e+05,1.922900e+05,1.937590e+05,1.951250e+05,1.964400e+05,NaN
259,Kosovo,XKX,"Population, total",SP.POP.TOTL,9.470000e+05,9.660000e+05,9.940000e+05,1.022000e+06,1.050000e+06,1.078000e+06,...,1.761474e+06,1.775680e+06,1.791000e+06,1.805200e+06,1.824100e+06,1.821800e+06,1.801800e+06,1.816200e+06,1.830700e+06,NaN
260,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5.172135e+06,5.260501e+06,5.351799e+06,5.446063e+06,5.543339e+06,5.643643e+06,...,2.297493e+07,2.360678e+07,2.425221e+07,2.490997e+07,2.557632e+07,2.624633e+07,2.691621e+07,2.758421e+07,2.825042e+07,NaN
261,South Africa,ZAF,"Population, total",SP.POP.TOTL,1.745686e+07,1.792067e+07,1.840161e+07,1.889928e+07,1.941298e+07,1.994230e+07,...,5.097082e+07,5.158466e+07,5.226352e+07,5.299821e+07,5.376740e+07,5.453957e+07,5.529122e+07,5.601547e+07,5.671716e+07,NaN
262,Zambia,ZMB,"Population, total",SP.POP.TOTL,3.044846e+06,3.140264e+06,3.240587e+06,3.345145e+06,3.452942e+06,3.563407e+06,...,1.345642e+07,1.385003e+07,1.426476e+07,1.469994e+07,1.515321e+07,1.562097e+07,1.610059e+07,1.659139e+07,1.709413e+07,NaN
263,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3.747369e+06,3.870756e+06,3.999419e+06,4.132756e+06,4.269863e+06,4.410212e+06,...,1.381060e+07,1.408632e+07,1.438665e+07,1.471083e+07,1.505451e+07,1.541168e+07,1.577745e+07,1.615036e+07,1.652990e+07,NaN

In [9]:
# Run this cell to see what the data looks like
df_population.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54211.0,55438.0,56225.0,56695.0,57032.0,57360.0,...,101453.0,101669.0,102053.0,102577.0,103187.0,103795.0,104341.0,104822.0,105264.0,NaN
1,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996351.0,9166764.0,9345868.0,9533954.0,9731361.0,9938414.0,...,28004331.0,28803167.0,29708599.0,30696958.0,31731688.0,32758020.0,33736494.0,34656032.0,35530081.0,NaN
2,Angola,AGO,"Population, total",SP.POP.TOTL,5643182.0,5753024.0,5866061.0,5980417.0,6093321.0,6203299.0,...,22549547.0,23369131.0,24218565.0,25096150.0,25998340.0,26920466.0,27859305.0,28813463.0,29784193.0,NaN
3,Albania,ALB,"Population, total",SP.POP.TOTL,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,...,2927519.0,2913021.0,2905195.0,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0,NaN
4,Andorra,AND,"Population, total",SP.POP.TOTL,13411.0,14375.0,15370.0,16412.0,17469.0,18549.0,...,84462.0,84449.0,83751.0,82431.0,80788.0,79223.0,78014.0,77281.0,76965.0,NaN

Make sure to scroll over to see what the last column looks like. That last column, called 'Unnamed: 62', doesn't look very useful and is filled with NaN values.

In [10]:
# TODO: Count the number of null values in each column
df_population.isnull().sum()

Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960                4
1961                4
1962                4
1963                4
1964                4
1965                4
1966                4
1967                4
1968                4
1969                4
1970                4
1971                4
1972                4
1973                4
1974                4
1975                4
1976                4
1977                4
1978                4
1979                4
1980                4
1981                4
1982                4
1983                4
1984                4
1985                4
                 ...
1989                4
1990                2
1991                2
1992                3
1993                3
1994                3
1995                2
1996                2
1997                2
1998                1
1999                1
2000                1
2001                1
2002                1
2003                1
2004                1
2005                1
2006                1
2007                1
2008                1
2009                1
2010                1
2011                1
2012                2
2013                2
2014                2
2015                2
2016                2
2017                2
Unnamed: 62       264
Length: 63, dtype: int64

It looks like every year column has at least one NaN value.

In [11]:
# TODO: Count the number of null values in each row
# HINT: In the sum method, use axis=1
df_population.isnull().sum(axis=1)

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
      ..
234    1
235    1
236    1
237    1
238    1
239    1
240    1
241    1
242    1
243    1
244    1
245    1
246    1
247    1
248    1
249    1
250    1
251    1
252    1
253    1
254    1
255    1
256    1
257    1
258    1
259    1
260    1
261    1
262    1
263    1
Length: 264, dtype: int64

And it looks like almost every row has only one null value. That is probably from the 'Unnamed: 62' column that doesn't have any relevant information in it. Next, drop the 'Unnamed: 62' column from the data frame.

In [12]:
# TODO: drop the 'Unnamed: 62' column from the data frame, 
# and save the results in the df_population variable

df_population = df_population.drop(['Unnamed: 62'],axis=1)

In [13]:
# Run this code cell.  
# This code outputs any row that contains a null value
# The purpose is to see what rows contain null values now that 
#   'Unnamed: 62' was dropped from the data.
df_population[df_population.isnull().any(axis=1)]

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
67,Eritrea,ERI,"Population, total",SP.POP.TOTL,1397491.0,1432640.0,1469645.0,1508273.0,1548187.0,1589179.0,...,4232636.0,4310334.0,4390840.0,4474690.0,NaN,NaN,NaN,NaN,NaN,NaN
108,Not classified,INX,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,Kuwait,KWT,"Population, total",SP.POP.TOTL,269618.0,301336.0,338296.0,379891.0,425235.0,473554.0,...,2652340.0,2818939.0,2998083.0,3191051.0,3395556.0,3598385.0,3782450.0,3935794.0,4052584.0,4136528.0
194,West Bank and Gaza,PSE,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,3596688.0,3702218.0,3811102.0,3927051.0,4046901.0,4169506.0,4294682.0,4422143.0,4551566.0,4684777.0
212,Serbia,SRB,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,7350222.0,7320807.0,7291436.0,7234099.0,7199077.0,7164132.0,7130576.0,7095383.0,7058322.0,7022268.0
223,Sint Maarten (Dutch part),SXM,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,33964.0,34238.0,34056.0,33435.0,34640.0,36607.0,37685.0,38824.0,39969.0,41109.0

# Conclusion 

This population data doesn't look too bad. Only six rows have missing values. In the transformation part of the lesson, you'll have to deal with these missing values somehow.

If you would like to see the solution file for this exercise, go to File->Open and click on 1_csv_exercise_solution.ipynb.

In the next exercise, you'll practice extracting data json and xml files.